### ISSUE TITLE
Event System

### ISSUE THREAD

**Issue by king601** [king601/AthensMC#7]
Let's create a calendar so people can see events we're hosting on the website.

Events should have:
- Name
- Host
- Activity (whatchu playin')
- Server tagging (snapshot, rrr, or modded). We can use these tags to display them inside an Event Well on the server page itself when there are events. 
- Start Timestamp (date+time)

Things to think about; 

Should whitelisted members be allowed to create their own events... or just staff?

**Comment by ChristopherCLee** [comment]
Using pro account...

Maybe a compromise - an "Official" tag for events that are official. Should also have the ability to link it so if people are streaming, people can click on the link and go to an HTML page or the Twitch or Beam stream.

**Comment by king601** [comment]
@ChristopherCLee I like the idea of linking the streaming.. was thinking previously about having a Showcase/Featured section where we could feature videos/images or streams on the server. 

Could also just have an official tag and then just have all upcoming events shared across each server page
