### ISSUE TITLE
Mailjet automation

### ISSUE THREAD

**Issue by king601** [king601/AthensMC#8]
When a user signs up they should be added to our Mailjet contact list for the campaigns.

Some example code I was shown by a friend

```
Mailjet::Contactslist_managecontact.create(id: YOUR_ID, action: "addforce", email: user.email, name: user.username, properties: {plan: "plan_name"})
```

This will allow us to auto subscribe users to our soon monthly email campaigns

**Comment by ChristopherCLee** [comment]
You should have an opt-in/out option so you are canspam compliant.

**Comment by geekweapon** [comment]
Agreed, you are opening yourself up to becoming a spammer without a proper opt-in/opt-out process.  This should be built into the app for users to drop in/out as they please.  Think mailchimp.

**Comment by king601** [comment]
Opting out can be done on the list with clicking the Unsubscribe button/link. I'll add an opt in/out into the sign in flow/manage account flow. 

It's only going to be used for big announcements like an upcoming one so I'm going to just opt everyone in and let everyone opt out from this point forward

**Comment by shakycode** [comment]
@king601 Right, but what you're not considering is you can't by law opt-in someone without their permission.  People have to signup and agree to opting in.  I don't think you'll have a problem with opting everyone in from a legal standpoint, but if you intend to grow your userbase you'll want to put the choice in their hands on sign-up.

**Comment by king601** [comment]
Yeah I agree and understand, it'll be a choice for sign up when I get it implemented. 

Just didn't have this planned when the first 200 users signed up, so they'll just be added for the first email and can opt out easily.
